import { createEvidencePack, buildProfileExport, normalizeSourceRecord } from "./capture.js";
import { runDoctor } from "./doctor.js";

const sourceSchema = { type: "object", required: ["id"], additionalProperties: true, properties: { id: { type: "string" }, type: { type: "string" }, locator: { type: "string" }, observed_at: { type: "string" }, metadata: { type: "object" }, fields: { type: "object" } } };
export function listCaptureTools() { return [
  { name: "capture.normalize", description: "Normalize an already-exported source record; never fetches.", inputSchema: { type: "object", required: ["source"], additionalProperties: false, properties: { source: sourceSchema } } },
  { name: "capture.evidence_pack", description: "Build a provenance-preserving evidence pack from already-exported sources.", inputSchema: { type: "object", required: ["sources"], additionalProperties: false, properties: { sources: { type: "array", items: sourceSchema }, profile: { type: "string", enum: ["repo-safe-summary", "internal-evidence-pack", "raw-local-only"] } } } },
  { name: "capture.doctor", description: "Check the installed capture-truth package.", inputSchema: { type: "object", additionalProperties: false, properties: {} } }
]; }
export async function callCaptureTool(name, args = {}) { if (name === "capture.normalize") { const normalized = normalizeSourceRecord(args.source); delete normalized.raw; normalized.raw_included = false; normalized.fields = sanitizeStructured(normalized.fields); normalized.metadata = sanitizeStructured(normalized.metadata); return jsonContent(normalized); } if (name === "capture.evidence_pack") { if (args.profile === "raw-local-only") throw new Error("raw-local-only is local-only and is not available through portable MCP."); const pack = createEvidencePack({ sources: args.sources }); return jsonContent(buildProfileExport(pack, args.profile ?? "repo-safe-summary")); } if (name === "capture.doctor") return jsonContent(await runDoctor()); throw new Error(`Unknown capture tool: ${name}`); }
function rawLikeKey(key) { return /^(?:body|content|raw|text|payload|data|document|html|markdown|description|message|prose|blob|contents?)$/i.test(String(key)) || /(?:raw|payload|body|content|document|html|markdown|prose)/i.test(String(key)); }
function sanitizeStructured(value) { if (Array.isArray(value)) return value.map(sanitizeStructured); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).filter(([key]) => !rawLikeKey(key)).map(([key, entry]) => [key, sanitizeStructured(entry)])); return value; }
function jsonContent(value) { return { content: [{ type: "text", text: JSON.stringify(value, null, 2) }] }; }
